markus-wa/demoinfocs-golang

- packet_handlers.go
https://github.com/SteamDatabase/GameTracking-CSGO/commit/0afcda44e79ca57fd4251550fa349bea76f6b7d2
```
WARNING: Unknown event "item_remove"
WARNING: Unknown event "item_remove"
WARNING: Unknown event "item_remove"
WARNING: Unknown event "item_remove"
WARNING: Unknown event "item_remove"
WARNING: Unknown event "item_remove"
WARNING: Unknown event "item_remove"
WARNING: Unknown event "item_remove"
```
> item_remove event was added

- common/common.go
- events/events.go
- packet_handlers.go
> Add item events

- datatables.go
- demoinfocs_test.go
- game_events.go
See #42 
@micvbang please check if this helps.
I had to do some more complicated code than you suggested but this should catch everything, hopefully.
> Issue 42 - Grenade entities not destoryed

- datatables.go
- sendtables/entity.go
See #38 
Cc @micvbang can you verify this works. I remember you originally bringing this up via Gitter.
> Issue 38 - Entity.Position() for CCSPlayer entities

- common/common.go
- datatables.go
- demoinfocs_test.go
- events/events.go
- examples/print-events/print_events.go
- fuzzy/team_switch.go
- game_events.go
- game_state.go
Hey!
Here's a draft of the implementation for the `ScoreUpdated` event.
Because of circular dependencies, I had to move `TeamState` to common.
What do you think? :slightly_smiling_face: 
Fixes #54
> Add ScoreUpdated event

- common/equipment.go
- datatables.go
Hey Markus!
I wanted to look at how often players zoom in. This seems to be what's needed :slightly_smiling_face:
> equipment: add ZoomLevel property

- metadata/maps.go
Updated version of the refactoring where the public variables are not dropped.
> metadata: refactoring

- game_events.go
- parser.go
Clean up the mess that is `Parser.handleGameEvent()`
> Parser: Refactor event handling

- common/common.go
> Fix divide by zero in common.DemoHeader.FrameTime

- events/events.go
- events/events_test.go
- game_events.go
> events: fix ItemPickup, ItemEquip & ItemRemove UniqueID() issue

- common/equipment.go
Without these changes all events report MP5-SD as unknown weapon
> MP5-SD support

- game_events.go
Also delayed `player_blind` event
Should finally fix #142 :)
> fix delayedEventHandlers not being updated

- game_events.go
- parser.go
- parsing.go
> Fix ItemEquip.Player == nil

- common/equipment.go
- events/events.go
> Kill.Killer may be nil, "worldspawn" Equipment should be EqWorld

- common/player.go
- common/player_test.go
- game_events.go
adds:
- Player.IsControllingBot()
- Player.ControlledBot()
fixes #164
> add Player bot utility functions

- game_state.go
> find player by handle: search in playersByUserID as a fallback (fixes #176)

- game_events.go
Solves issue #180 . Additionally, formatted the file because comments were getting too close to the code lines.
> delayed all bomb events until there are players in the game

- datatables.go
- demoinfocs_test.go
- game_events.go
- net_messages.go
- parser_test.go
- parsing.go
- stringtables.go
> core: don't panic, return errors instead

- README.md
this is mostly to test the new PR check changes (reviewdog etc.)
> README: add link to contributors

- net_messages.go
- parser_test.go
- parsing.go
- stringtables.go
> core: bring back panicking behvaiour from pre-1.8.0

- pkg/demoinfocs/game_events.go
Hey there @xavier-rodet & @BestAwperEver 
I think have finally found a way to detect bomb damage reliably.
Please note that this branch uses the v2 API, so you may need to upgrade.
I will merge this in a bit and will post an update on #169 when a new version with the fix is out.
> Bomb Damage Detection (+Fall Damage)

- .github/workflows/protobuf.yml
> Protobuf Bot

- README.md
- examples/print-events/print_events.go
- pkg/demoinfocs/datatables.go
- pkg/demoinfocs/game_events.go
- pkg/demoinfocs/game_state.go
- pkg/demoinfocs/net_messages.go
<details>
<summary>example output (print-events)</summary>
```
Map: de_dust2
Chat - [CT]SiBaby says: tüm türk arkadaşlarıma merhaba
Chat - ? says: can you give us t
Chat - [CT]valens says: !switch
Chat - ? says: thanks
[CT]sharof0444 <USP-S (HS)> [T]stew
[CT]sharof0444 <USP-S (HS)> ?
[T]SiBaby <Glock-18 (HS)> Metin
sherpss <USP-S (HS)> [T]SiBaby
1foxey <USP-S (HS)> [T]valens
1foxey <USP-S (HS)> [T]TaRiK
Round finished: winnerSide=CT ; score=1:0
Chat - 1foxey says:  it induces physical effects such as a faster reaction time, fatigue resistance, and increased muscle strength.
Chat - Metin says: wait valens infusion says she knows you too
Chat - Metin says: this is bonkers
Chat - [T]valens says: where's mare
Chat - Metin says: sleepy sleep
1foxey <MP9> [T]SiBaby
1foxey <MP9> [T]TaRiK
[T]stew …
```
> full support for POV demos

- .golangci.yml
- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/common/player_test.go
> common: try to improve accuracy of Player.IsDucking()

- pkg/demoinfocs/common/common.go
- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/common/player_test.go
(#248)
Worked perfectly on a demo I tested =>
> CT Black Fart Yellow
> CT KMA Purple
> T Ryba Orange
> CT Xelf Blue
> CT Cheuveulu Orange
> T Nozyyy🦁 Yellow
> T Slink1019 Blue
> T Kamik Green
> T Stog CS.DEALS Purple
> CT socio* linux <3 Green
Let me know how should I test that ?
> add color function for common.Player

- .golangci.yml
- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/datatables_test.go
- pkg/demoinfocs/debug_on.go
- pkg/demoinfocs/events/events.go
- pkg/demoinfocs/events/events_test.go
- pkg/demoinfocs/user_messages.go
simply dispatch the raw RoundImpactScoreData event
> Operation Broken Fang: RoundImpactScoreData

- .golangci.yml
- pkg/demoinfocs/common/hostage.go
- pkg/demoinfocs/common/hostage_test.go
- pkg/demoinfocs/datatables.go
- pkg/demoinfocs/events/events.go
- pkg/demoinfocs/fake/game_state.go
- pkg/demoinfocs/game_events.go
- pkg/demoinfocs/game_state.go
- pkg/demoinfocs/game_state_interface.go
- pkg/demoinfocs/game_state_test.go
Hi!
This PR allows to access hostages information and adds events related to hostage maps.
You can find a hostage demo here:
https://www85.zippyshare.com/v/ebimojQq/file.html
Thank you
> Give some love to hostage maps

- pkg/demoinfocs/events/events.go
- pkg/demoinfocs/game_events.go
> don't panic for unknown bombsites, raise ParserWarn event instead

- pkg/demoinfocs/common/common.go
- pkg/demoinfocs/common/common_test.go
> common: add GrenadeProjectile.Velocity() function

- README.md
> Add PureSkill.gg to list of projects

- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/common/player_test.go
> common: add Player.PositionEyes() func + fix Player.Position() docs

- pkg/demoinfocs/stringtables.go
fixes https://github.com/markus-wa/demoinfocs-golang/security/code-scanning/5 and https://github.com/markus-wa/demoinfocs-golang/security/code-scanning/4
> pkg/demoinfocs/stringtables: fix dangerous int conversion

- examples/README.md
- examples/common.go
- examples/heatmap/README.md
- examples/heatmap/heatmap.go
- examples/heatmap/heatmap_test.go
- examples/nade-trajectories/README.md
- examples/nade-trajectories/nade_trajectories.go
> examples: use radar-overviews.csgo.saiko.tech for radar images and offsets

- pkg/demoinfocs/demoinfocs_test.go
- pkg/demoinfocs/parser.go
- pkg/demoinfocs/parsing.go
- pkg/demoinfocs/s2_commands.go
- pkg/demoinfocs/sendtables/st_parser.go
- pkg/demoinfocs/sendtables2/class.go
- pkg/demoinfocs/sendtables2/entity.go
- pkg/demoinfocs/sendtables2/field.go
- pkg/demoinfocs/sendtables2/field_decoder.go
- pkg/demoinfocs/sendtables2/field_patch.go
- pkg/demoinfocs/sendtables2/field_path.go
- pkg/demoinfocs/sendtables2/field_reader.go
- pkg/demoinfocs/sendtables2/field_state.go
- pkg/demoinfocs/sendtables2/field_type.go
- pkg/demoinfocs/sendtables2/huffman.go
- pkg/demoinfocs/sendtables2/panicf.go
- pkg/demoinfocs/sendtables2/parser.go
- pkg/demoinfocs/sendtables2/quantizedfloat.go
- pkg/demoinfocs/sendtables2/reader.go
- pkg/demoinfocs/sendtables2/serializer.go
- pkg/demoinfocs/stringtables.go
Currently, this code results in `unable to find existing entity` panics.
GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore go test -run TestS2 ./pkg/demoinfocs -s2dem `pwd`/test/cs-demos/003606749594131628213_2016071942.dem
Any help with getting a demo to parse entities would be appreciated.
Sample CS2 demos: https://drive.google.com/drive/folders/15sgA_cJXUnF7SldkT5Ov-UiQAJBTLz1a
> WIP: s2 entity (crashes right now ...)

- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/sendtables2/entity.go
- pkg/demoinfocs/sendtables2/field_decoder.go
Hi!
- `player.Position()` is now working
- Fix some player props such as money, MVP... not returning correct values
Test code:
```go
package main
import (
"errors"
"fmt"
"os"
"time"
demoinfocs "github.com/markus-wa/demoinfocs-golang/v3/pkg/demoinfocs"
"github.com/markus-wa/demoinfocs-golang/v3/pkg/demoinfocs/events"
)
func main() {
var err error
f, err := os.Open("./faze-vs-legends-m3-dust2.dem")
checkError(err)
defer f.Close()
p := demoinfocs.NewParser(f)
defer p.Close()
_, err = p.ParseHeader()
checkError(err)
p.RegisterEventHandler(func(e events.Kill) {
killer := e.Killer
if killer != nil {
position := e.Killer.Position()
color, _ := e.Killer.ColorOrErr()
fmt.Printf("%s x:%f y:%f z:%f $:%d S:%d ping:%d color:%d k:%d d:%d a:%d mvp:%d\n", killer.Name, position.X, position.Y, position.Z, …
```
> fix: working player position + some player fields

- pkg/demoinfocs/common/common_test.go
- pkg/demoinfocs/common/inferno.go
- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/datatables.go
- pkg/demoinfocs/events/events.go
- pkg/demoinfocs/events/events_test.go
- pkg/demoinfocs/fake/game_state.go
- pkg/demoinfocs/fake/participants.go
- pkg/demoinfocs/game_state.go
- pkg/demoinfocs/game_state_interface.go
- pkg/demoinfocs/parser.go
- pkg/demoinfocs/participants_interface.go
This PR adds support for projectiles/infernos tracking.
The following events should work:
- `GrenadeProjectileBounce`
- `GrenadeProjectileDestroy`
- `GrenadeProjectileThrow`
- `InfernoStart`
- `InfernoExpired`
Differences I noticed with Source 1:
- `m_hOwnerEntity` is the pawn entity ID, that's why I added a `FindByPawnHandle` function
- To retrieve the correct weapon type based on the projectile entity, we should use `CBodyComponent.m_hModel` as `m_nModelIndex` doesn't exist anymore. The mapping between the weapon's type and the model value is stored in a new `equipmentTypePerModel` map and populated when a grenade entity is created.
- The game events `inferno_startburn`/`inferno_expire` are present but definitely not reliable, for example, the`userid` field is missing
Test code:
```go …
```
> feat: projectiles/infernos support

- pkg/demoinfocs/common/player.go
Essentially checking pawn entity's `"m_bSpottedByMask.000X"` property instead of player entity's `"m_bSpottedByMask.00X"`. Also `"m_unRoundStartEquipmentValue"` and `"m_unFreezetimeEndEquipmentValue"`.
> adjust IsSpottedBy for source 2

- pkg/demoinfocs/common/inferno.go
- pkg/demoinfocs/common/inferno_test.go
- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/datatables.go
- pkg/demoinfocs/events/events.go
- pkg/demoinfocs/net_messages.go
- pkg/demoinfocs/parser.go
- pkg/demoinfocs/parsing.go
- fix player pawn entity ID not updated
- fix bomb carrier always nil
- handle ConVar message
- add missing round end reason values
-  fix `player.isAlive()` not 100% accurate
- Update header's playback values at the end of parsing for demos without `CDemoFileInfo` message 
- Fix inferno thrower may be nil
> more source 2 support

- pkg/demoinfocs/common/player.go
Small fixes to avoid possible crashes.
> fix: possible crash player props

- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/common/player_test.go
- pkg/demoinfocs/net_messages.go
- pkg/demoinfocs/parser.go
- Adds some player properties to retrieve rank information.  
Values in comments will have to be updated when CS2 is released, and all game modes are available.
- Dispatch `RankUpdate` events
Thanks
> feat: add player rank properties

- pkg/demoinfocs/datatables.go
> fix missing PlayerConnect events

- pkg/demoinfocs/sendtables2/field_decoder.go
Fix https://github.com/markus-wa/demoinfocs-golang/issues/433
> fix: simulation time decoder tickrate

- pkg/demoinfocs/game_events.go
Fix https://github.com/markus-wa/demoinfocs-golang/issues/511
> fix: dispatch player disconnect events for bots

- pkg/demoinfocs/game_events.go
> fix: update Connected flag on bots disconnection

- pkg/demoinfocs/datatables.go
reported here https://github.com/akiver/cs-demo-manager/issues/774
> fix: panic on round end draw events

- pkg/demoinfocs/datatables.go
> fix some POV crashes

- examples/heatmap/heatmap_test.go
- examples/map_metadata_test.go
- examples/nade-trajectories/nade_trajectories_test.go
- pkg/demoinfocs/datatables.go
fix https://github.com/akiver/cs-demo-manager/issues/863
> fix: possible nil player in game events

- pkg/demoinfocs/net_messages.go
Noticed with demos recorded with MatchZy
> fix: missing chat message events

- pkg/demoinfocs/game_events.go
> fix: missing game events

- pkg/demoinfocs/datatables.go
https://github.com/akiver/cs-demo-analyzer/issues/23
the planter controller handle may be invalid
> fix: panic in bomb m_bStartedArming prop update handler
