markus-wa/demoinfocs-golang

- common/common.go
`WARNING: Unknown weapon decoy_projectile`
Maybe it's damage taken from a decoy exploding?
> There seems to be a decoy_projectile weapon too

- events/events.go
- game_events.go
- parser.go
The solution with using the entity doesn't really work. For some nades (e.g. molotov), the entity is deleted. If we have the ID, while we cannot access the entity, we can at least relate the different events (throw, explode, expire).
> Revert to use entity id instead of entity

- sendtables/entity.go
Added a way to get the current prop value. The current implementation only stores prop value for values that we have created a RegisterPropertyUpdateHandler on.
> Added prop value to PropertyEntry

- common/structs.go
- datatables.go
As I argued for GrenadeProjectiles, I find it very useful as a consumer of the library to have unique ids on grenade projectiles. I find the same to be the case for equipment :slightly_smiling_face:
> Add unique id to Equipment.

- common/structs.go
- datatables.go
- events/events.go
- game_events.go
- game_state.go
I was looking into tracking the bomb's position, and it seems like it's something that could be useful to include in the library.
As you can see from the TODOs, I found a slight problem with the current interface of `Property.OnUpdate`. It seems like it could be useful to return a `HandlerIdentifier`, as is already being done in the event dispatcher.
I'm not sure where you would like this to go, but since I'm actively using branch v1.0.0 now, I branched out from here and pointed the PR here as well :slightly_smiling_face:
> Add GameState.Bomb()

- datatables.go
- demoinfocs_test.go
- game_events.go
- sendtables/entity.go
See #38 & #42
* Delete nade projectiles & infernos at end of round to remove immortal nades
* `Entity.Position()` for `CCSPlayer` entities
> Backport fixes for #38 & #42

- README.md
- datatables.go
- demoinfocs_test.go
- demopacket.go
- events/events.go
- examples/entities/README.md
- examples/entities/entities.go
- examples/heatmap/heatmap.go
- examples/nade-trajectories/nade_trajectories.go
- examples/print-events/print_events.go
- fuzzy/team_switch.go
- game_events.go
- parser.go
- parsing.go
- stringtables.go
See #45
Cc @micvbang - Any feedback appreciated.
I also decided to switch from past to present tense, removing many 'ed' suffixes, except where necessary so the events aren't confused with something else.
E.g. if it were `BombDefuse` instead of `BombDefused` it could be mistaken for the start of defusing.
> Clean up event naming

- .travis.yml
Go 1.10 allows us to remove the dependency to goverage.
> Travis: Use go 1.10's coverpkg

- .travis.yml
- README.md
Avoid downloading test data for the end user.
> Speed up 'go get'

- stringtables.go
Due to an error when porting StatsHelix's demoinfocs, players were
skipped if there was a 'gap' between the string-table entries.
So if the string-table's userdata at index 3 was empty for example,
players at index 4 and above would be ignored.
> Fix players being skipped in processStringTable

- game_events.go
Hey Markus!
I just found that in map 1 (dust2) of this demo https://www.hltv.org/matches/2322780/liquid-vs-astralis-esl-pro-league-season-7-finals, the demo recording is started _after_ players have connected. 
This means that no events are dispatched until `playersByUserID` has length > 0. `playersByUserID` is updated _later_ than `Parser.rawPlayers`, and does not necessarily contain any players before interesting events (e.g. `MatchStart`), although there are players on the server.
Here's a suggestion for a fix
> game_events: begin dispatching events after any 'player_' event

- datatables.go
Hey Markus!
As far as I can tell, `m_bFireIsBurning` is not triggered when it starts burning, but it only appears in the list if it actually _is_ burning. So it seems that it should be defaulted to true :slightly_smiling_face:
> datatables: default inferno fires to IsBurning=true

- common/inferno.go
- common/inferno_test.go
Hey!
I just found that the update to using `z = 0` in inferno positions (7625fa0aead) makes the convex hull algorithm yield a weird result. This PR should fix it :slightly_smiling_face: 
The following screenshots are taken with with z=0 and z=1, respectively
> Inferno: fix bug where 0 z-dimension gives weird convex hull

- common/gamerules.go
- datatables.go
- events/events.go
- game_state.go
- parsing.go
Hey Markus!
I just stumbled upon a datatable that I'd never seen before. It seems like this datatable holds "facts" that have to be true in order for the demo to be rendered correctly in-game. 
My guess is that some of our problems w.r.t. e.g. missing `RoundEnd` events can be solved (or mitigated) using some of these fields.
I have been looking for a reliable way to detect team side switches for a long time, and I believe that the secret was hidden in `CCSGameRulesProxy` all along!
I've tested the following with approx 50 demos. They all give the same result: both `GameHalfEnd` and `TeamSideSwitch` are dispatched correctly after 15 rounds played (and are dispatched correctly for overtime as well!)
> events: Add TeamSideSwitch, GameHalfEnd, GamePhaseChanged

- datatables.go
- events/events.go
- game_state.go
Hey Markus!
I just ran into another funky demo [1]. In this demo, none of the previous MatchStart events are sent. But, as I had hoped for (yay!), the game rules datatable seems to contain the "truth" about certain things, among them whether a match was started or not. This PR makes it possible to read the `m_bHasMatchStarted` value from the game rules :slightly_smiling_face: 
[1]: https://www.hltv.org/matches/2327377/tyloo-vs-big-starseries-i-league-season-6
> events: Add MatchStartChanged

- .travis.yml
- examples/README.md
- examples/mocking/README.md
- examples/mocking/collect_kills.go
- examples/mocking/mocking_test.go
- fake/game_state.go
- fake/parser.go
- fake/parser_test.go
- fake/participants.go
- game_state.go
- game_state_interface.go
- go.mod
- go.sum
- parser.go
- parser_interface.go
- participants_interface.go
pinging @micvbang 
This is my counter proposal to #57.
As we've discussed there I looked into interface generation to avoid godoc and Intellisense issues.
I found that another nice side-effect of this approach is that the impact on consumers is a bit lighter as they won't need to change their variable/field types from `*Parser` to `Parser` now (though for `GameState` and `Participants` that 'issue' remains).
I also added a new package `mock` that provides basic but (hopefully) extendable mocks for the various interfaces, so not everyone needs to re-implement them unless there's a specific need.
Lastly I added an example on how to use the mocks to write unit tests: https://github.com/markus-wa/demoinfocs-golang/tree/mockable-api/examples/mocking
For the last two I took a lot of inspiration …
> Mockable API

- events/events.go
- events/events_test.go
- game_events.go
- game_state.go
- parser.go
- parsing.go
Changes to `PlayerFlashed`:
- new attribute `Attacker`
- new utility function `FlashDuration()` - returns `Player.FlashDurationTime()`
Also fixes the issue with `PlayerFlashed.Player.FlashDuration` being 0 in
most cases by waiting with dispatching the events until the end of the tick.
Fixes #70 & #71
@quancore please verify
> events: add Attacker & FlashDuration() to PlayerFlashed event

- common/inferno.go
- common/inferno_test.go
- examples/nade-trajectories/nade_trajectories.go
- go.mod
- go.sum
`examples/nade-trajectories` broke because the result of `ConvexHull2D()` wasn't ordered counter-clock wise anymore
- `ConvexHull2D()`: return clockwise ordered `r2.Point` slice
- `ConvexHull3D()`: return `quickhull.ConvexHull`
fixes #85
@micvbang can you verify this works for you as well?
One thing to note is that as it no longer returns a `s2.Loop` the start position is only there once, before the start and end of the loop was the same position. Depending on how your drawing code works you might need to change something.
> common: fix regression with Inferno convex hulls

- common/common.go
- common/common_test.go
- events/events.go
- game_events.go
- game_state.go
- game_state_interface.go
- game_state_test.go
- parser.go
Useful for when we have a TeamState but don't know which team's it is
from context.
Fixes #76 
@quancore: does this address the issue as expected?
> common: add function TeamState.Team()

- datatables.go
- parsing.go
- sendtables/entity.go
- sendtables/sendtables.go
Instead of checking after each tick whether there's new players to be added to `Parser.gameState.playersByUserID` we can (hopefully) do this in `Parser.bindNewPlayer()` instead.
This seems to avoid **some** game-events with `nil` values for players.
It also prevents an issue where `Participants.ByEntityID()` got out of sync and contained pointers to old players.
Also, as a bonus, it improves performance by about **5-10% (!)** according to my benchmarks.
> Parser: Refactor Parser.gameState.playersByUserID population

- .travis.yml
- common/player.go
- datatables.go
- datatables_test.go
- game_events.go
- game_state.go
- game_state_test.go
- parser.go
- parsing.go
- sendtables/entity.go
- sendtables/entity_interface.go
- sendtables/fake/entity.go
- Fixes #98 
- Makes `Player.IsBot` more accurate by also checking the GUID
- ~~Adds `PlayerConnect` event for bots.~~ the change for this didn't do what I expected, it ended up sending wrong events instead.
- events: delay PlayerTeamChange until end of tick
- team IDs of other players changing teams in the same tick might not have changed yet
- player entities might not have been re-created yet after a reconnect
Depends on #94
> Parser: Player tracking improvements

- common/player.go
- common/player_test.go
- datatables.go
- datatables_test.go
- events/events_test.go
- fake/parser_test.go
- game_state_test.go
This should fix ~~any~~ most issues with `Player.IsBlinded()`.
It may still return wrong values if the demo's header is lacking the tickrate.
It also adds another utility function `Player.FlashDurationTimeRemaining()` which returns the remaining duration of the flash. This may be useful as the player may be able to partially see if the remaining time is fairly low.
> common: fix Player.IsBlinded() inaccuracies

- common/player.go
- datatables.go
- datatables_test.go
- fake/participants.go
- game_events.go
- game_state.go
- game_state_test.go
- participants_interface.go
In some cases we get events for players shortly after they disconnect.
We now keep these players stored in the gameState so we can still put them into future events.
Also adds `Participants.Connected()` and changes `Participants.All()` to return disconnected players as well.
fixes #69
> events: fix nil Player values after disconnect

- common/player.go
- common/player_test.go
- datatables.go
- datatables_test.go
- events/events.go
- examples/entities/README.md
- examples/entities/entities.go
- fake/game_state.go
- fake/parser.go
- fake/participants.go
- game_events.go
- game_state.go
- game_state_test.go
- participants_interface.go
- sendtables/entity.go
- sendtables/entity_interface.go
- sendtables/fake/doc.go
- sendtables/fake/entity.go
- sendtables/fake/property.go
- sendtables/property_interface.go
Fixes #114 
* Added `PlayerSpottersChanged` event
* Added helper functions to `common.Player`
- `IsSpottedBy(*Player) bool`
- `HasSpotted(*Player) bool`
* Added helper functions to `Participants`
- `SpottersOf(*Player) []*Player`
- `SpottedBy(*Player) []*Player`
* `Entity.FindProperty()` has been deprecated, use `Entity.FindPropertyI()` instead which returns `IProperty` instead of `*Property`
* `Entity.Properties()` has been deprecated, use `Entity.PropertiesI()` instead which returns `[]IProperty` instead of `[]Property`
`Entity.Properties()` and `Entity.FindProperty()` have been deprecated and should be replaced with `Entity.PropertiesI()` and `Entity.FindPropertyI()` which return interfaces so we can mock the returned values in unit tests.
> Player spotting information [Player.IsSpottedBy()]

- common/common.go
- common/common_test.go
- common/player.go
- common/player_test.go
- game_state.go
Depends on #121 
Fixes #115
* Added helper functions to `common.Player` for easily retrieving additional data (#115):
- `Player.IsInBombZone()`
- `Player.IsInBuyZone()`
- `Player.IsWalking()`
- `Player.IsScoped()`
- `Player.CashSpentThisRound()`
- `Player.CashSpentTotal()`
* Added helper functions to `common.TeamState` for retrieving information over all members of a team:
- `TeamState.Members()`
- `TeamState.CurrentEquipmentValue()`
- `TeamState.RoundStartEquipmentValue()`
- `TeamState.FreezeTimeEndEquipmentValue()`
- `TeamState.CashSpentThisRound()`
- `TeamState.CashSpentTotal()`
>  common: add helper functions for Player and TeamState

- common/equipment.go
- common/gamerules.go
Added two functions to retrieve all gamephase- and weapon names to allow direct export along with match data.
Now with new names and its own pull request :stuck_out_tongue_closed_eyes:
> Export functions for equipment and game phase names

- datatables.go
Added two functions to retrieve all gamephase- and weapon names to allow direct export along with match data.
Equipment.AmmoReserve has been left uninitialized at 0 so far, so i thought i might add that as well.
Not sure if i missed something aside from properly recreating the Interface, reserve ammo update seemed pretty straightforward.
> Equipment.AmmoReserve

- fake/game_state.go
- game_state.go
- game_state_interface.go
Added IGameState.GamePhase() function to retrieve current game phase
Like #134 without .currentDefuser
> GameState: Allow accessing .gamePhase

- common/equipment.go
- common/equipment_test.go
- common/player.go
- datatables.go
- game_events.go
- game_events_test.go
fixes #145
- AmmoInMagazine2() returns 1 for grenades
- AmmoReserve2() returns 'Owner.LeftAmmo[AmmoType] - 1' for grenades
This means if a player has two flashbangs:
- `AmmoInMagazine2()` will return 1
- `AmmoInReserve2()` will return 1
- total amount of flashbangs (2) = `AmmoInMagazine2() + AmmoInReserve2()`
> common: add new ammo functions to Equipment for grenades

- common/equipment.go
- common/equipment_test.go
- datatables.go
- game_events.go
This PR makes getPlayerWeapon() check for alternative weapons
e.g. USP for P2000, silenced M4 variant etc.
fixes #148 & fixes #149
> fix PlayerHurt.Weapon not working for alternate weapons

- common/player.go
- datatables.go
- game_events.go
- parser.go
fixes #162
We just assume the player which cannot be found is a bot and skip it, since all human players were parsed correctly in the demo where this problem was encountered.
> fix nil pointer dereference for valid demo

- datatables_test.go
- demoinfocs_test.go
- fake/participants.go
- game_state.go
- game_state_test.go
- participants_interface.go
New method `IParticipants.AllByUserID()` gives read-only access to the all current players (including spectators etc.) by user id.
> add IParticipants.AllByUserID() method (#167)

- datatables.go
Recently in newer demos I faced a strange issue when all players' knives were recognized as `EqUnknown` by the library. I'm not sure why it suddenly stopped working properly (is it possible that some csgo internals have changed?), but this fixed it for me 🙂
> added "CKnife" server class mapping to EqKnife

- common/equipment.go
[HLTV link](https://www.hltv.org/matches/2329006/clg-red-vs-star-spangled-fraggers-wesg-2018-united-states-regional-finals-female)
clg-red-vs-star-spangled-fraggers-m2-train-p1.dem
At tick number 118792 there is a `PlayerHurt` event with `EqUnknown` weapon. In the game the player was hurt with molotov projectile, which is stored as `"molotov_projectile"` in the raw event data. However, in the library we don't have mapping for this string (although we have it for `"molotovprojectile"`). I assumed that the similar problem may arise with other types of projectiles so I added appropriate mapping for them as well.
> added *_projectile equipment mapping for grenades

- go.mod
- go.sum
- parser.go
- parser_test.go
- parsing.go
fixes #190
Example:
code:
```go
p := NewParser(demoFile)
p.RegisterEventHandler(func(e interface{}) {
p.GameState().Entities()[-1].ID()
}
p.ParseToEnd()
```
output:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa53718]
goroutine 7 [running]:
github.com/markus-wa/godispatch.callConsumerCode.func1()
/home/mark/go/pkg/mod/github.com/markus-wa/godispatch@v1.2.1/dispatch.go:104 +0x88
panic(0xb2f920, 0xc0001ae130)
/opt/go/src/runtime/panic.go:679 +0x1b2
github.com/markus-wa/godispatch.callConsumerCode.func1() …
```
> core: don't suppress ConsumerCodePanic in recoverFromPanic

- datatables.go
Hotfix for the recent internal changes.
Without it we have many players with unknown weapons. Before the internal changes we had an actual array with fixed memory layout so every entity ID had a fixed pointer to an equipment, which doesn't hold now, so when we first have a player binded (with unknown weapons at the moment) and then we bind their weapons, the pointers we have in player's `rawWeapons` still point to the unknown weapons.
> changing the existing weapon instead of creating a new one

- pkg/demoinfocs/common/common.go
- pkg/demoinfocs/common/common_test.go
- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/common/player_test.go
- pkg/demoinfocs/datatables.go
- pkg/demoinfocs/events/events.go
- pkg/demoinfocs/events/events_test.go
- pkg/demoinfocs/game_events.go
- pkg/demoinfocs/game_events_test.go
- pkg/demoinfocs/stringtables.go
- converter funcs in `common`
- utility funcs on `Player` and `RankUpdate` for quick access to both 32-bit and 64-bit variants
> SteamID Improvements

- README.md
- examples/entities/entities.go
- examples/heatmap/heatmap.go
- examples/nade-trajectories/nade_trajectories.go
- examples/net-messages/netmessages.go
- examples/print-events/print_events.go
- pkg/demoinfocs/examples_test.go
- pkg/demoinfocs/fake/parser.go
- pkg/demoinfocs/parser.go
- pkg/demoinfocs/parser_interface.go
- pkg/demoinfocs/parser_test.go
- pkg/demoinfocs/parsing.go
Parser.Close() will call msgDispatcher.RemoveAllQueues() to terminate the goroutine handling net-messages.
It needs to be called by the user before discarding the Parser.
fixes #216
> core: add Parser.Close() to fix memory leak

- README.md
- examples/entities/entities.go
- examples/heatmap/heatmap.go
- examples/nade-trajectories/nade_trajectories.go
- examples/net-messages/netmessages.go
- examples/print-events/print_events.go
- examples_test.go
- fake/parser.go
- parser.go
- parser_interface.go
- parser_test.go
- parsing.go
`Parser.Close()` will call `msgDispatcher.RemoveAllQueues()` to terminate the goroutine handling net-messages.
It needs to be called by the user before discarding the Parser.
> core: add Parser.Close() to fix memory leak (#216) [backport to v1]

- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/common/player_test.go
Adds the ability to get a player's crosshair code. 
If the player doesn't have a crosshair (legacy demo) an empty string is returned
> Add Player.CrosshairCode() to pull players current crosshair code

- go.mod
- go.sum
note: this is just precautionary and to reduce the noise in Snyk.
To my knowledge there are/were no vulnerable code paths.
- CVE-2020-9283
- CVE-2020-9283
- CVE-2020-14040
- CVE-2019-11254
> deps: upgrade vulnerable deps

- .golangci.yml
- go.mod
- go.sum
- pkg/demoinfocs/demoinfocs_test.go
- pkg/demoinfocs/parser.go
- pkg/demoinfocs/parser_interface.go
- pkg/demoinfocs/parsing.go
- tests: fix linting issues
- parsing: fix lint errors
- core: fix deadlock caused by multiple calls to Parser.Cancel() (#276)
> fix deadlock caused by multiple calls to Parser.Cancel()

- pkg/demoinfocs/demoinfocs_test.go
- pkg/demoinfocs/events/events.go
- pkg/demoinfocs/stringtables.go
fixes regression introduced in 0515f18b2e9fdeea6b7a549adfd9c902a1eac19f where we lost player name changes
> stringtables: capture player name changes and raise new PlayerNameChange event

- pkg/demoinfocs/parsing.go
fix `ParseToEnd()` not returning errors that happen during `SyncAllQueues()`
> core: return errors in ParseToEnd() that happen during SyncAllQueues()

- pkg/demoinfocs/matchinfo.go
> matchinfo: fix bad hex conversion in MatchInfoDecryptionKey()

- examples/encrypted-net-messages/enc_net_msg.go
- examples/encrypted-net-messages/enc_net_msg_test.go
- pkg/demoinfocs/demoinfocs_test.go
- pkg/demoinfocs/events/events.go
- pkg/demoinfocs/net_messages.go
> raise ParserWarn instead of error on bad net-message decryption key

- go.mod
- go.sum
- pkg/demoinfocs/common/equipment.go
The prior uniqueID for equipment wasn't guaranteed to be unique.
This is
1. guaranteed to be unique
2. produced in a sortable order
3. easily marshallable
4. requires few extra dependencies.
> Adding UniqueID2 for Equipment

- pkg/demoinfocs/common/equipment.go
This commit adds recoil index. This is easy to interpret: increasing recoil index means more recoil. Decreasing recoil index means player isn't holding fire button. 
Should I also add recoil vectors? I considered adding functions for `player.Entity.PropertyValueMust("localdata.m_Local.m_aimPunchAngle").VectorVal` and
`player.Entity.PropertyValueMust("localdata.m_Local.m_viewPunchAngle").VectorVal`, but decided against that because interpreting those vectors requires handling angle wrap around and scaling (see https://davidbdurst.com/blog/csknow_recoil.html). Thoughts? I wasn't sure if this amount of interpretation belongs in the parser.
> Adding Recoil Index Property of Weapon

- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/common/player_test.go
Spent some time working out the most consistent way to calculate ADR, and kept running into issues. But found that the game tracked m_iMatchStats_Damage_Total. So added methods for pulling that as well as utility damage.
This makes really trivial to create those damage line graphs, for total damage, and utility damage. 
I added automated tests for these as well.
> Adds new methods for getting total damage, and utility damage

- pkg/demoinfocs/events/events.go
Hi @markus-wa!
A tiny PR to add the hit group value for the neck.
It has been noticed in this [issue](https://github.com/akiver/CSGO-Demos-Manager/issues/598) that it's possible to have a hit group value set to `8`, which seems to correspond to the neck.
Thank you, and happy new year!
> feat: add neck hitbox

- pkg/demoinfocs/sendtables/fake/entity.go
Hello
This PR fixes `NewEntityWithProperty`. This function can't work properly because the methods `PropertyValue` and `PropertyValueMust` need the name of the property as a parameter.
> Fix NewEntityWithProperty (sendtables/fake)

- pkg/demoinfocs/datatables.go
- pkg/demoinfocs/parsing.go
- pkg/demoinfocs/s2_commands.go
- pkg/demoinfocs/sendtables2/entity.go
- pkg/demoinfocs/sendtables2/quantizedfloat.go
Hi!
Trying to parse these 3 CS2 demos https://www.hltv.org/matches/2365256/faze-vs-legends-steelseries-cs2-legends-vs-champions-2023 on the `s2` branch currently results in errors.
Test code:
```go
package main
import (
"errors"
"fmt"
"os"
"time"
demoinfocs "github.com/markus-wa/demoinfocs-golang/v3/pkg/demoinfocs"
common "github.com/markus-wa/demoinfocs-golang/v3/pkg/demoinfocs/common"
"github.com/markus-wa/demoinfocs-golang/v3/pkg/demoinfocs/events"
"github.com/markus-wa/demoinfocs-golang/v3/pkg/demoinfocs/sendtables"
)
func main() {
var err error
f, err := os.Open("./faze-vs-legends-m3-dust2.dem")
checkError(err)
defer f.Close()
p := demoinfocs.NewParser(f)
defer p.Close()
_, err = p.ParseHeader()
checkError(err)
p.RegisterEventHandler(func(e events.Kill) {
var hs string
if …
```
> Improve source 2 support

- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/parsing.go
- pkg/demoinfocs/s2_commands.go
- pkg/demoinfocs/stringtables.go
- Update header fields from the `CDemoFileHeader` message (should be the first message received)
- Detect POV demos the same way as CSGO demos
- Dispatch `PlayerInfo` events on `userinfo` string table updates
Thank you
> feat: update header info from CDemoFileHeader and detect POV demos

- pkg/demoinfocs/common/common.go
- pkg/demoinfocs/common/common_test.go
- pkg/demoinfocs/common/entity_util.go
- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/events/events_test.go
- pkg/demoinfocs/game_state.go
- pkg/demoinfocs/parser.go
- add `IsSource2` method to `demoInfoProvider`, which calls `isSource2` method of `parser`
- add `demoInfoProvider` to `TeamState` (we will probably need to add it to other places as well)
- use `IsSource2` in `Player` and `TeamStats` to control which property of which entity should be used (there is still much to do in that regard)
> add IsSource2 method to demoInfoProvider

- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/datatables.go
- pkg/demoinfocs/events/events.go
- pkg/demoinfocs/game_state.go
* fix: more player's props access without crash using `IsSource2` added by @BestAwperEver in https://github.com/markus-wa/demoinfocs-golang/pull/395 👍 
* fix: update player's team based on `m_iTeamNum` prop changes (was based on `player_team` game events)
* feat: add OvertimeCount that indicates how many overtime started
> feat: more Source 2 support

- pkg/demoinfocs/common/player.go
Adapt some player functions to Source 2.
> feat: more source 2 player props support

- pkg/demoinfocs/common/player.go
At least sometimes `p.PlayerPawnEntity()` returns `nil`, so, in that case, we could still fall back to the `m_bPawnIsAlive` player property. I can't say anything about the accuracy but at least we don't crash :)
> get player m_bPawnIsAlive property when pawn entity is nil

- pkg/demoinfocs/datatables.go
- pkg/demoinfocs/game_events.go
- pkg/demoinfocs/game_state.go
- pkg/demoinfocs/parser.go
- pkg/demoinfocs/parsing.go
This PR mimic the following Source 1 game events with CS2 demos based on prop updates:
- `WeaponFire`
- `RoundStart`
- `RoundEnd`
- `RoundEndOfficially`
- `BombPickup`
- `BombDropped`
- `BombPlantBegin`
- `BombPlantAborted`
- `BombPlanted`
- `BombDefuse`
- `BombExplode`
- `BombDefuseStart`
- `BombDefuseAborted`
- `FlashExplode`
Test code:
```go
package main
import (
"errors"
"fmt"
"os"
"time"
demoinfocs "github.com/markus-wa/demoinfocs-golang/v3/pkg/demoinfocs"
"github.com/markus-wa/demoinfocs-golang/v3/pkg/demoinfocs/events"
)
func main() {
var err error
f, err := os.Open("./faze-vs-legends-m2-nuke.dem")
checkError(err)
defer f.Close()
p := demoinfocs.NewParser(f)
defer p.Close()
_, err = p.ParseHeader()
checkError(err)
p.RegisterEventHandler(func(e events.RoundStart) { …
```
> feat: mimic some source 1 game events

- pkg/demoinfocs/common/equipment.go
Just a small fix for the correct identification of a planted c4 as a weapon in (some?) Source 2 demos
> add planted_c4 weapon name to weapon mapping

- .github/workflows/ci.yml
- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/datatables.go
- pkg/demoinfocs/game_events.go
- pkg/demoinfocs/game_state.go
- pkg/demoinfocs/stringtables.go
Hi! It should fix https://github.com/markus-wa/demoinfocs-golang/issues/407 https://github.com/markus-wa/demoinfocs-golang/issues/410 https://github.com/markus-wa/demoinfocs-golang/issues/411
The main changes are:
- Remove `PawnEntityID` from `Player` and make `player.PlayerPawnEntity()` retrieve the pawn entity based on `m_hPlayerPawn` so we don't have to keep in sync `PawnEntityID` when the entity is re-created (re-connection)
- Move the `bindNewPlayerControllerS2` logic into `bindNewPlayerPawnS2`.
The player's controllers are created once at the beginning, and then the player's pawn entities are created/destroyed when a player is connected/disconnected.  
It was incorrect to dispatch connection events when a player's controller is created.
- Do not erase player's entry in`rawPlayers` …
> fix: players may not be found

- pkg/demoinfocs/parsing.go
It looks like demos affected by https://github.com/markus-wa/demoinfocs-golang/issues/409 are still parsable even if a message decompression failed.
This PR replaces the panic with a warning.
Note: I had the issue with only 3 demos, maybe @Run1e you can try it with your affected demos?
> feat: warn and continue parsing on msg decompression failure

- pkg/demoinfocs/datatables.go
- pkg/demoinfocs/events/events.go
Hi!
This PR adds an `ItemRefund` event.
It's dispatched when a player refunds his purchase during the buy time and is available only with CS2 demos.
Thanks
> feat: add ItemRefund event

- pkg/demoinfocs/common/player_test.go
- pkg/demoinfocs/datatables.go
- pkg/demoinfocs/datatables_test.go
- pkg/demoinfocs/events/events.go
- Fix the bombsite field in game events always `BombsiteUnknown` when  `disableMimicSource1GameEvents` is set to `true`. Bounding boxes information are now in the server class `CBombTarget`. It was not an issue when `disableMimicSource1GameEvents` is `false` (the default), as it uses props to detect bombsite.
- Fix a rare case where the bombsite in `BombPlantBegin` events is unknown (when `disableMimicSource1GameEvents` is `false`). It happened in this [de_mirage demo](http://replay190.valve.net/730/003641925298976457430_0293543650.dem.bz2) at round 4 when the player struggled to plant on A near boxes. As a fallback (when `m_nWhichBombZone` is `0`), I detect the closest site based on the distance between the player's position and bombsites.
> fix: possible unknown bombsite in BombPlantBegin event

- pkg/demoinfocs/common/hostage.go
- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/common/player_test.go
- Fix panic when calling `hostage.Leader()` with CS2 demos
- Add `IsGrabbingHostage` to `Player`
Thx!
> fix: possible panic hostage.Leader() with CS2 demos

- pkg/demoinfocs/datatables.go
- pkg/demoinfocs/game_events.go
- pkg/demoinfocs/game_state.go
When `disableMimicSource1GameEvents` is `false` (the default), the events `RoundFreezetimeChanged` were dispatched before `RoundStart` events.
> fix: dispatch freezetime events after round start events

- pkg/demoinfocs/sendtables2/parser.go
- pkg/demoinfocs/sendtables2/serializer.go
This PR removes for loops from getFieldPathForName by introducing new map to serializer which helps to find fields by their name.
This results in ~25% faster parsing. Here are numbers from my machine for current master:
File size: 81 MB
Elapsed: 3.665982666s
File size: 107 MB
Elapsed: 4.7228615s
File size: 159 MB
Elapsed: 10.646743625s
And here is this branch results: 
File size: 81 MB
Elapsed: 2.72868975s
File size: 107 MB
Elapsed: 3.623294709s
File size: 159 MB
Elapsed: 7.519242125s
> Remove for loop from getFieldPathForName

- pkg/demoinfocs/common/equipment.go
- pkg/demoinfocs/common/equipment_test.go
Currently it is not possible to check whether a weapon has a silencer attached or not.
* A new equipment method Silenced() which returns true if the entity value "m_bSilencerOn" is true.
> Silenced weapon

- pkg/demoinfocs/common/player.go
Experiments show that m_iPawnArmor of the Player entity tends to be updated a few ticks later than m_ArmorValue of the Pawn entity.
> Source 2: Fix Player.Armor() sometimes being a few ticks outdated

- pkg/demoinfocs/common/equipment.go
with this fix, `AmmoInMagazine() + AmmoReserve()` returns the correct amount of nades again with CS2
> fix nade counts for CS2

- pkg/demoinfocs/common/player.go
It looks like in the past 12 hours almost every cs2 demo from Faceit (maybe even every single one, I'm not sure about that) crashes with `panic: interface conversion: interface {} is nil, not uint64` because of `Any` field of the `m_iPawnHealth` property of any player controller entity always being `nil`, so I'm proposing this as a hotfix.
Example match: https://www.faceit.com/en/cs2/room/1-f0438560-e84a-451b-b5f4-572917e9ad32
> check pawn entity health

- pkg/demoinfocs/common/inferno.go
- pkg/demoinfocs/common/inferno_test.go
This PR lets users to extract the raw list of individual fires, allowing them to perform custom calculations on the raw data. This can be very useful when e.g. wishing to visualize the data with higher fidelity than convex hull, and for doing statistics
> inferno/Fires: add List() to return raw list of fires

- pkg/demoinfocs/sendtables2/class.go
- pkg/demoinfocs/sendtables2/parser.go
Another cache, provides noticeable performance increase and reduces memory usage:
Before: 
80 MB   2.72s
107 MB  3.82s
159 MB  8.27s
After: 
80 MB   2.18s
107 MB  2.99s
159 MB  6.49s
Memory before: 4754.88MB 
Memory after:   3495.16MB
(for one demo file - 159 MB)
> FieldPath name cache

- pkg/demoinfocs/datatables.go
Fixed an issue in CS2 where Player.Inventory would not include any weapons with which the player started.
As a simple test run the following program (for my own test, I used https://www.hltv.org/matches/2367165/rhyno-vs-perroflautas-aveiro-techdays-cup-2023 map 2 anubis):
```
func main() {
demoFilePath := flag.String("demo", "", "path to demo file")
flag.Parse()
demoFile, err := os.Open(*demoFilePath)
if err != nil {
panic(err)
}
parser := demoinfocs.NewParser(demoFile)
if err != nil {
panic(err)
}
parser.RegisterEventHandler(func(_ events.RoundStart) {
fmt.Printf("Round start: %d\n", parser.GameState().TotalRoundsPlayed()+1)
var players []*common.Player
players = append(players, parser.GameState().TeamTerrorists().Members()...)
players = append(players, …
```
> CS2: Player Inventory now includes initial loadout at the beginning of the game

- pkg/demoinfocs/sendtables2/entity.go
- pkg/demoinfocs/sendtables2/parser.go
- pkg/demoinfocs/sendtables2/serializer.go
Cache indeed provides the same performance increase as just removing the check.
But I have decided to put in on serializer object, cause the check does not seem to be dependant on entity and there are far less serializer objects created than entities.
> cache fieldName checks

- pkg/demoinfocs/common/inferno.go
In the last 24 hours, I've been observing many demos that don't have `m_fire{X,Y,Z}Delta.XXXX` properties, and instead have `m_firePositions.XXXX` (older demos lack this property). This PR attempts to use the new property if the entity has it. I'm not 100% sure about the correctness of the data (see image: the CT died from the fire but the position of the death looks a bit off), but it looks good enough for now and is certainly better than crashing :)
> use m_firePositions property in compatible demos

- pkg/demoinfocs/common/common.go
- pkg/demoinfocs/datatables.go
This PR adds the possibility to track the timings of a grenade trajectory. This can be useful if you e.g. want to be able to show the trajectory as-it-happens during a replay.
I didn't want to make an API breaking change, so I added it in a separate list that tracks the contents of `GrenadeProjectile.Trajectory`. 
I added the `PointInTime` struct instead of just logging the frame id or time in seconds s.t. the user can get whichever of the two values they want. This struct could alternatively be called e.g. `PointInDemo`, `Timing`, or something else
> grenade trajectories: collect timings of each location

- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/datatables.go
fix https://github.com/markus-wa/demoinfocs-golang/issues/461
For some reason at tick 0 a `CPlantedC4` entity is created but players are spawning and the bomb is not planted.
Also update the rank type values in the comment.
> fix: bomb planter not found

- pkg/demoinfocs/datatables.go
Alternative to fix https://github.com/markus-wa/demoinfocs-golang/pull/467.
This PR moves the logic inside the `OnUpdate` callback of `m_hController` outside to avoid calling pawn entity properties lifecycle when we should not.
The pawn entity props that we need to listen now retrieve the player associated with the pawn entity from the current `m_hController` prop value.
> fix: retrieve and update correct player after disconnection/bot take over

- pkg/demoinfocs/common/common_test.go
- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/common/player_test.go
- pkg/demoinfocs/datatables.go
- pkg/demoinfocs/parsing.go
- pkg/demoinfocs/s2_commands.go
Related to https://github.com/markus-wa/demoinfocs-golang/issues/406
It looks like the player's velocity will not be networked in CS2 demos any time soon, so this PR adds it by tracking the player's positions.
To ensure accuracy, I first tried with a CS:GO demo and compared values by printing the velocity at each frame:
```go
// VelocityTemp is the new S2 implementation, the only diff is the framerate being ~32 instead of 64
fmt.Println("Expected X/Y:", player.Velocity().X, player.Velocity().Y, "Got X/Y: ", player.VelocityTemp().X, player.VelocityTemp().Y)
```
<details>
<summary>Partial output</summary>
Expected X/Y: -19.653369903564453 28.658458709716797 Got X/Y:  -15.64716902168722 22.81130925206571
Expected X/Y: -35.63056945800781 51.95634078979492 Got X/Y:  -31.59869694205065 …
> feat: add player velocity

- pkg/demoinfocs/datatables.go
This relates to #472. 
This PR sets an equipment's owner to nil in cases where the equipment is destroyed or dropped, making `GameState().Weapons()` give a _slightly more_ correct view of a player's weapons.
Note: in my experience it still shows duplicate knives and starter pistols.
EDIT: I wonder if the duplicate starter weapons are due to player deaths? 🤔
> datatables cs2: update equipment owner

- pkg/demoinfocs/datatables.go
NOTE: this is not 100% accurate yet, but it's a big step in the right direction.
Thanks to esbengc for describing the required logic!
> datatables cs2: rewrite player equipment tracking

- pkg/demoinfocs/datatables.go
Hi!
The crash has been reported [here](https://github.com/akiver/cs-demo-manager/issues/724).
The owner may point to a disconnected player, this PR retrieves the good owner when the weapon entity is destroyed.
Thanks
> fix: possible panic due to incorrect weapon's owner

- pkg/demoinfocs/common/equipment.go
- pkg/demoinfocs/common/equipment_test.go
Bug reported [here](https://github.com/akiver/cs-demo-manager/issues/721).
It's a weird CS2 bug - the weapon's name in `player_death` events can have a suffix that is part of the killer's name.
Example:
```go
fmt.Println(geh.gameState().IngameTick(), killer.Name, data["weapon"].GetValString())
```
Output:
```
1631 𝑽𝑰𝑷 落日下恋人相拥，无人在意这是黄昏 deagle_vip
1920 goparojotu3 deagle
2043 𝑽𝑰𝑷 罗锅 deagle_vip
2348 老恋歌 glock
2378 罗锅被查内务出列 usp_silencer
2491 年𝑽𝑰𝑷 修记者 glock_vip
2916 喝杯奶茶再说吧 usp_silencer
3326 罗锅被查内务出列 usp_silencer
3419 老恋歌 glock
4402 年𝑽𝑰𝑷 修记者 glock_vip
4898 𝑽𝑰𝑷 呢嘛，叔输输。 deagle_vip
5160 𝑽𝑰𝑷 落日下恋人相拥，无人在意这是黄昏 deagle_vip
5291 goparojotu3 deagle
5554 goparojotu3 deagle
5647 𝑽𝑰𝑷 罗锅 deagle_vip
5674 goparojotu3 deagle
6216 𝑽𝑰𝑷 怎么有人打GO都能破防啊 glock_vip
6326 𝑽𝑰𝑷 罗锅 deagle_vip
6601 喝杯奶茶再说吧 usp_silencer
6906 …
```
> fix: weapon may be incorrect in kill events

- pkg/demoinfocs/common/common_test.go
- pkg/demoinfocs/common/hostage.go
- pkg/demoinfocs/common/hostage_test.go
- pkg/demoinfocs/common/inferno.go
- pkg/demoinfocs/common/inferno_test.go
- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/common/player_test.go
- pkg/demoinfocs/events/events_test.go
- pkg/demoinfocs/parser.go
The demo from this [issue](https://github.com/akiver/cs-demo-manager/issues/725) has the problem described and fixed in this [PR](https://github.com/markus-wa/demoinfocs-golang/pull/489).
The other PR fixes the first panic, but another happens due to a missing prop when a player takes control of a bot.
The prop `m_iControlledBotEntIndex` expected in `player.ControlledBot()` doesn't exist in CS2 demos.
As a replacement I use the prop `m_hOriginalControllerOfCurrentPawn`.
I also had to change the signature of `FindPlayerByHandle` to `FindPlayerByHandle(handle uint64) *Player` since the controllers are `uin64` values.
> fix: panic on bot_takeover events

- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/common/player_test.go
- pkg/demoinfocs/datatables.go
It should fix #481, #458 and this [issue](https://github.com/akiver/cs-demo-manager/issues/723) (same problem as #458).
I noticed this thing with the demo from https://github.com/akiver/cs-demo-manager/issues/723:
As you can see the last player is disconnected but still visible on the scoreboard.
When this kind of disconnection happens, the player pawn entity is "invalidated" - it points to a `CBaseViewModel` instance rather than a `CCSPlayerPawn` one.
This is why in #458 and https://github.com/akiver/cs-demo-manager/issues/723 the properties don't exist and it panics.
This PR:
- Update `player.IsConnected` when the pawn entity is invalid
- Verify that `m_hPawn` is valid, otherwise it means `m_hPlayerPawn` will point to a `CBaseViewModel`
Thanks
> fix: Participants().Playing() may returned disconnected players

- pkg/demoinfocs/common/equipment.go
- pkg/demoinfocs/common/equipment_test.go
Following https://github.com/markus-wa/demoinfocs-golang/pull/490.
- It's not always a suffix - it can be a prefix.
- The suffix/prefix is not the killer's name but the words `vip` or `default` (there may be others).
- The team's name may also be part of the suffix/prefix
Noticed with demos coming from https://github.com/akiver/cs-demo-manager/issues/727.  
Example with this one https://mega.nz/file/LZFlhATB#aCO-g1hoGohndAKXJVUHzLCcbyzH-n7cGi9ZWO5UdSM.
Weapon's name from game events:
```
5e_vip_usp_silencer
5e_default_deagle
5e_vip_xm1014
5e_default_mp9
5e_default_galilar
5e_vip_m4a1_silencer
5e_vip_ak47
```
> fix: possible invalid weapon in kill events

- pkg/demoinfocs/datatables.go
Bot controller entities can be destroyed:
```
96322 player_controller_destroy 12 Baroud 0
107866 player_controller_destroy 14 Bank 0
```
If we don't update the prop `Connected`, the bot will still be in the slice returned by `Playing()`.   
As a result, calling a player's function that relies on its pawn entity such as `EquipmentValueCurrent()` may result in a panic as the pawn entity doesn't exists anymore.
Noticed with this demo https://mega.nz/file/uBdF3TBT#aoGpmJ6PKaNIMqPdZsVxHyhiv7DbxO3M9jJNWAOIhb0 and the following code:
```go
p.RegisterEventHandler(func(e events.RoundStart) {
fmt.Println(p.GameState().TeamCounterTerrorists().CurrentEquipmentValue())
fmt.Println(p.GameState().TeamTerrorists().CurrentEquipmentValue())
})
```
ref https://github.com/akiver/cs-demo-manager/issues/727
> fix: set player connected flag to false when controller is destroyed

- pkg/demoinfocs/sendtables2/entity.go
Fixes issue https://github.com/markus-wa/demoinfocs-golang/issues/501
Explanation: https://github.com/markus-wa/demoinfocs-golang/issues/501#issuecomment-1935327804
I would be glad if someone test it if it properly works for older demos and any other cases.
Cs2 instead of continuing does similar thing to csgo:
https://github.com/perilouswithadollarsign/cstrike15_src/blob/f82112a2388b841d72cb62ca48ab1846dfcc11c8/engine/client.cpp#L1562-L1589
I think simple continue is fine :)
> Support PVS bits

- .github/workflows/ci.yml
To make sure we stay compatible with 1.20
> ci: run on Go 1.20.x

- pkg/demoinfocs/datatables.go
- pkg/demoinfocs/demoinfocs_test.go
- pkg/demoinfocs/events/events.go
- pkg/demoinfocs/game_events.go
- pkg/demoinfocs/sendtables2/entity.go
- pkg/demoinfocs/stringtables.go
> CS2 POV demo support

- pkg/demoinfocs/events/events.go
- pkg/demoinfocs/parsing.go
To avoid panicking when the protobuf messages need to be updated
> feat: skip unknown demo commands messages

- pkg/demoinfocs/common/hostage.go
- pkg/demoinfocs/common/hostage_test.go
ref https://github.com/akiver/cs-demo-manager/issues/839
`hostage.Leader()` may return `nil` when a player is grabbing a hostage.
To match the CSGO behavior (it's not nil) I fallback to the new CS2 prop `m_hHostageGrabber`.
> fix: hostage leader possibly nil

- pkg/demoinfocs/game_events.go
Since the last update, I've been encountering many demos in which after a player has disconnected, and then reconnected, they wouldn't be registered in the `rawPlayers` field. Thus, in many cases, there were `nil` players in some events (e. g. all grenade events).
I investigated this a little and found out that seemingly the only place we could get information to add the player back to the `rawPlayers` (at least in particular demos I've been using) is inside the `player_connect` handler, which was disabled for s2 demos in #499. I'm assuming this was done because the user ids for players have been changed in the February, 6 update from being in the lower digits to 652xx.
I'm not sure what exactly has been changed in the last update (my guess is the `userinfo` string table is not parsed as …
> workaround for `userid` in `player_connect`

- pkg/demoinfocs/demoinfocs_test.go
- pkg/demoinfocs/events/events.go
- pkg/demoinfocs/game_events.go
- pkg/demoinfocs/stringtables.go
fix https://github.com/markus-wa/demoinfocs-golang/issues/539 https://github.com/markus-wa/demoinfocs-golang/issues/532 https://github.com/markus-wa/demoinfocs-golang/issues/522 and maybe https://github.com/markus-wa/demoinfocs-golang/issues/525 (i can't reproduce the issue).
Tests of the project https://github.com/akiver/cs-demo-analyzer/pull/10/checks are also green.
This PR reverts the logic in `parseStringTable` introduced in v4.1.0 and instead if a panic occurs while parsing a stringtable, we recover and dispatch a warning.
I'm not 100% sure but sometimes data seems corrupted and skipping it seems fine.
I didn't find a logic that doesn't panic when parsing stringtables for both CSTV and POV demos, that's why I decided to go for the recover solution.
> fix: incomplete stringtables parsing

- pkg/demoinfocs/events/events.go
- pkg/demoinfocs/game_events.go
Literally what's written in the title.
Needed it for a little personal project, saw there was a "TODO" message for this event so assumed it's probably something others also want and here it is.
Not sure if there are any unit tests I should've updated, seems like there aren't but if there are I'll be happy to do it.
> feat: implement player_sound event

- .github/workflows/ci.yml
Run the https://github.com/akiver/cs-demo-analyzer tests in parallel from the CI workflow.
The purpose is to detect possible regressions.
Tests take [~2m20](https://github.com/markus-wa/demoinfocs-golang/actions/runs/9134318674/job/25119608783) when demos are cached and [~3m20](https://github.com/markus-wa/demoinfocs-golang/actions/runs/9134079035/job/25118883009) otherwise.
The cache will hit most of the time as new demos are not added very often.
> ci: run csda tests

- pkg/demoinfocs/s2_commands.go
Fixes #555 
All messages (SVC/UserMessages/GameEvents etc.) found in a demo packet are sorted based on their priority (ported from [dotabuff/manta](https://github.com/dotabuff/manta)). The used sorting function `sort.Slice()`  performs an unstable sort which might cause messages of the same priority to be reordered in arbitrary order.  This PR changes sorting function to `sort.SliceStable()`.
This unstable sort behaviour breaks POV demos while not affecting normal demos for some reason - someone can investigate further.
I tested it on broken POV demo that was provided with issue and 9 more that I had available - they all correctly parsed after this change.
> fix: stable sort messages

- pkg/demoinfocs/events/events.go
- pkg/demoinfocs/game_events.go
- pkg/demoinfocs/net_messages.go
- pkg/demoinfocs/parser.go
- feat: dispatch `BulletDamage` events added in the last update
- feat: add `SayText`/`SayText2` and `ChatMessage` events for CS2 demos. Chat messages are now available in recent Valve demos (and it's not encrypted like csgo).
> feat: add BulletDamage event + chat messages events

- pkg/demoinfocs/datatables.go
Make sure to create/update players in gameState (`playersByEntityID`, `playersByUserID`) on connection status changes.
Sometimes players raw info are not available on controller entity creation so it would result in missing players in `gameState.playersByUserID`.
It may be related to player disconnection as the affected player got disconnected at the beginning of the demo.
fix https://github.com/akiver/cs-demo-manager/issues/904
> fix: possible nil player in game events on rare occasion

- pkg/demoinfocs/common/equipment.go
The Kukri knife was added sometime ago and because of that I'm getting a warning whenever a player is using it in the demo:
`unknown equipment with index 526`
526 is the id for that knife in the items file
> Add Kukri's knife to equipment map

- pkg/demoinfocs/common/equipment.go
- pkg/demoinfocs/game_events.go
- pkg/demoinfocs/net_messages.go
- pkg/demoinfocs/user_messages.go
This fix all warnings about nil values in game events such as `Kill`, `PlayerHurt`... in the cs-demo-analyzer project.
> fix: possible nil players/weapons fields in some events

- examples/viewmodel-settings/README.md
- examples/viewmodel-settings/viewmodel_settings.go
- pkg/demoinfocs/common/player.go
- pkg/demoinfocs/common/player_test.go
This pr introduces functionality to extract player viewmodel settings (offsets and field of view)
* Added `ViewmodelOffset` and `ViewmodelFOV` methods to the `Player` struct to retrieve viewmodel settings. These methods return zero values for CS:GO demos or when player data is unavailable.
* Added relevant tests
* Added example + readme
> feat: Add ability to retrieve player viewmodel settings
